const chatTypes = {
  CHAT_FETCH_START: "CHAT_FETCH_START",
  CHAT_FETCH_SUCCESS: "CHAT_FETCH_SUCCESS",
  CHAT_FETCH_FAILURE: "CHAT_FETCH_FAILURE",
  SET_CURRENT_CHAT: "SET_CURRENT_CHAT",
};

export default chatTypes;
