const userTypes = {
    START_LOGIN: "START_LOGIN",
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    FAILURE_LOGIN: "FAILURE_LOGIN",
    START_REGISTER: "START_REGISTER",
    SUCCESS_REGISTER: "SUCCESS_REGISTER",
    FAILURE_REGISTER: "FAILURE_REGISTER",
    PROFILE_UPDATE_START: "PROFILE_UPDATE_START",
    PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
    PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILURE",
    LOGOUT: "LOGOUT"
}

export default userTypes;
